/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-bright": "#3a3939",
        "on-tertiary": "#003828",
        "on-secondary-fixed-variant": "#6200bc",
        "on-error-container": "#ffdad6",
        "surface": "#131313",
        "surface-tint": "#4cd6ff",
        "on-tertiary-fixed-variant": "#00513c",
        "on-secondary-fixed": "#290055",
        "on-primary-container": "#00566a",
        "on-background": "#e5e2e1",
        "inverse-surface": "#e5e2e1",
        "surface-container-lowest": "#0e0e0e",
        "surface-container-low": "#1c1b1b",
        "error": "#ffb4ab",
        "background": "#131313",
        "error-container": "#93000a",
        "secondary-fixed": "#eddcff",
        "on-tertiary-fixed": "#002116",
        "on-primary-fixed-variant": "#004e60",
        "on-surface-variant": "#bbc9cf",
        "secondary-container": "#6e06d0",
        "surface-container-highest": "#353534",
        "tertiary-fixed-dim": "#00e1ab",
        "surface-container-high": "#2a2a2a",
        "primary": "#a4e6ff",
        "secondary-fixed-dim": "#d8b9ff",
        "surface-variant": "#353534",
        "outline": "#859399",
        "tertiary-fixed": "#36ffc4",
        "on-secondary": "#450086",
        "primary-container": "#00d1ff",
        "surface-dim": "#131313",
        "secondary": "#d8b9ff",
        "inverse-primary": "#00677f",
        "inverse-on-surface": "#313030",
        "primary-fixed": "#b7eaff",
        "on-primary": "#003543",
        "on-tertiary-container": "#005a42",
        "on-primary-fixed": "#001f28",
        "surface-container": "#201f1f",
        "primary-fixed-dim": "#4cd6ff",
        "on-secondary-container": "#d5b5ff",
        "tertiary-container": "#00daa5",
        "on-surface": "#e5e2e1",
        "on-error": "#690005",
        "tertiary": "#00f9be",
        "outline-variant": "#3c494e",
        "warning": "#ffc107"
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"]
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
}
